name: belajar_matika
description: "Game Sederhana."
publish_to: "none"
version: 1.1.2

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.3.0
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  google_mobile_ads: ^5.3.1
  http: ^1.3.0
  logger: ^2.5.0
  lottie: ^3.2.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/animations/congrats.json
    - assets/animations/wrong.json
    - assets/animations/hello.json
    - assets/icons/
    # - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logomatika.png" # Sesuaikan dengan path dan nama file ikon Anda
  adaptive_icon_background: "#FFFFFF" # Warna latar belakang untuk ikon adaptif (Android)
  adaptive_icon_foreground: "assets/icons/logomatika_foreground.png" # Ikon foreground untuk Android (opsional)
